### PR TITLE
Chapter one corrections

### PR DESCRIPTION
**Pull request by Tenison**
Corrections were made to the Intro and chapter one of the documentation.

### CODE REVIEW

**Comment by rck** [comment]
Hi Tenison,

I rebased your work on top of our internal changes, squashed the two commits, and selectively picked the ones I thought that still make sense: https://github.com/LINBIT/linbit-documentation/commit/b2e431816579fe56967c675454c6f720f561ad92

Thanks, rck

**Comment by Tenison** [comment]
ok. Do I need to do anything

**Comment by rck** [comment]
no, all done, thanks

**Comment by anvithks** [comment]
#SODACODE-PR-ACCEPTED
@rck  could you please add the labels `SODACODE2022` and `SODALOW` to this PR.

**Pull request closed without merging**
